@baseUrl = http://localhost:3000/api/v1

GET {{baseUrl}}/account HTTP/1.1
TOKEN:"eyJUeXAiOiJKV1QiLCJBbGciOiJIUzI1NiIsIkN0eSI6IiJ9.eyJhdXRoIjp7Ik5hbWUiOiJhZG1pbiIsIlJvbGUiOiJhZG1pbiJ9LCJpYXQiOjE2ODMzNzEyODh9.JhusptrjlvIPzZGJDaLe-mlKU7tsemId8__nB57dJao"

###

POST {{baseUrl}}/account HTTP/1.1
Content-Type: application/json

{
    "Name" : "admin",
    "Username": "admin",
    "Password": "admin123"
}

###
POST {{baseUrl}}/account HTTP/1.1
Content-Type: application/json
TOKEN:"eyJUeXAiOiJKV1QiLCJBbGciOiJIUzI1NiIsIkN0eSI6IiJ9.eyJhdXRoIjp7Ik5hbWUiOiJhZG1pbiIsIlJvbGUiOiJhZG1pbiJ9LCJpYXQiOjE2ODMzNzEyODh9.JhusptrjlvIPzZGJDaLe-mlKU7tsemId8__nB57dJao"

{
    "Name" : "sigi",
    "Username": "Sigi",
    "Password": "Sigipass123"
}

###
PATCH {{baseUrl}}/account/6456075f7855bb0e7f3e17b3 HTTP/1.1

###
DELETE {{baseUrl}}/account/64561b23493102983a61ab59 HTTP/1.1

###
POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json

{
    "username":"Sigi",
    "password":"Sigipass123"
}
###
GET {{baseUrl}}/user/donggala/destinations HTTP/1.1

###
GET {{baseUrl}}/user/sigi/destinations/6456376168883f2d510dc505 HTTP/1.1